**Run the following two cells before you begin.**

In [1]:
%autosave 10

Autosaving every 10 seconds


In [2]:
import pandas as pd
import numpy as np

______________________________________________________________________
**First, import your data set and define the sigmoid function.**
<details>
    <summary>Hint:</summary>
    The definition of the sigmoid is $f(x) = \frac{1}{1 + e^{-X}}$.
</details>

In [156]:
# Import the data set
import numpy as np #numerical computation
import pandas as pd #data wrangling
import matplotlib.pyplot as plt #plotting package
#Next line helps with rendering plots
%matplotlib inline
import matplotlib as mpl #add'l plotting functionality
mpl.rcParams['figure.dpi'] = 400 #high res figures
df = pd.read_csv(r'C:\Users\sujith\Desktop\Technocolabs\problem2\Project-Data-Set-Repository-master\Project-Data-Set-Repository-master\Data set\cleaned_data.csv')

In [157]:
# Define the sigmoid function
def sigmoid(X):
    Y = 1 / (1 + np.exp(-X))
    return Y

In [158]:
X = df[['PAY_1','LIMIT_BAL']]
y = df[['default payment next month']]

In [159]:
X

PAY_1  LIMIT_BAL
0          2      20000
1         -1     120000
2          0      90000
3          0      50000
4         -1      50000
...      ...        ...
26659      0     220000
26660     -1     150000
26661      4      30000
26662      1      80000
26663      0      50000

[26664 rows x 2 columns]

In [160]:
lb_scale = X['LIMIT_BAL']/100000
lb_new = pd.DataFrame(lb_scale)
lb_new

LIMIT_BAL
0            0.2
1            1.2
2            0.9
3            0.5
4            0.5
...          ...
26659        2.2
26660        1.5
26661        0.3
26662        0.8
26663        0.5

[26664 rows x 1 columns]

In [165]:
new = X.drop(columns=['LIMIT_BAL'],axis=1)


In [168]:
new_X = pd.concat([new,lb_new],axis=1)

In [185]:
new_X

PAY_1  LIMIT_BAL
0          2        0.2
1         -1        1.2
2          0        0.9
3          0        0.5
4         -1        0.5
...      ...        ...
26659      0        2.2
26660     -1        1.5
26661      4        0.3
26662      1        0.8
26663      0        0.5

[26664 rows x 2 columns]

In [186]:
y

default payment next month
0                               1
1                               1
2                               0
3                               0
4                               0
...                           ...
26659                           0
26660                           0
26661                           1
26662                           1
26663                           1

[26664 rows x 1 columns]

**Now, create a train/test split (80/20) with `PAY_1` and `LIMIT_BAL` as features and `default payment next month` as values. Use a random state of 24.**

In [187]:
# Create a train/test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(new_X, y, test_size=0.2, random_state=0)

______________________________________________________________________
**Next, import LogisticRegression, with the default options, but set the solver to `'liblinear'`.**

In [188]:
from sklearn.linear_model import LogisticRegression
my_lr = LogisticRegression()
my_lr

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [189]:
my_new_lr = LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

______________________________________________________________________
**Now, train on the training data and obtain predicted classes, as well as class probabilities, using the testing data.**

In [190]:
# Fit the logistic regression model on training data
my_new_lr.fit(X_train,y_train)

F:\anaconda\New folder\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [212]:
# Make predictions using `.predict()`
pred = my_new_lr.predict(X_test)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [192]:
# Find class probabilities using `.predict_proba()`
probs = my_new_lr.predict_proba(X_test)

In [193]:
new_X.shape[0]

26664

______________________________________________________________________
**Then, pull out the coefficients and intercept from the trained model and manually calculate predicted probabilities. You'll need to add a column of 1s to your features, to multiply by the intercept.**

In [194]:
# Add column of 1s to features
x=pd.DataFrame(np.ones((new_X.shape[0],1)),columns=['ones'])

In [195]:
x.shape

(26664, 1)

In [196]:
type(new_X)

pandas.core.frame.DataFrame

In [197]:
type(x)

pandas.core.frame.DataFrame

In [198]:
X_new = pd.concat([new_X,x],axis=1)

In [199]:
X_new

PAY_1  LIMIT_BAL  ones
0          2        0.2   1.0
1         -1        1.2   1.0
2          0        0.9   1.0
3          0        0.5   1.0
4         -1        0.5   1.0
...      ...        ...   ...
26659      0        2.2   1.0
26660     -1        1.5   1.0
26661      4        0.3   1.0
26662      1        0.8   1.0
26663      0        0.5   1.0

[26664 rows x 3 columns]

In [200]:
# Get coefficients and intercepts from trained model
coeff = my_new_lr.coef_
intercept = my_new_lr.intercept_

In [202]:
coeff

array([[ 0.68628689, -0.1766934 ]])

In [203]:
intercept

array([-1.10264262])

In [204]:
# Manually calculate predicted probabilities
x1 = new_X.iloc[0]['PAY_1']
x2 = new_X.iloc[0]['LIMIT_BAL']

In [205]:
x1

2.0

In [206]:
x2

0.2

In [207]:
inter = X_new.iloc[0]['ones']
inter

1.0

In [232]:
val = coeff[0][0]*new_X.iloc[0]['PAY_1'] + coeff[0][0]*new_X.iloc[1]['LIMIT_BAL'] +intercept[0]
val

1.09347542813218

In [233]:
z= sigmoid(val)

In [234]:
z #for sigmoid 0 to 1 means z < 0.5 means 0 if grater tahn 0.5 means 1

0.7490356022760172

In [235]:
probs[0]

array([0.92131608, 0.07868392])

______________________________________________________________________
**Next, using a threshold of `0.5`, manually calculate predicted classes. Compare this to the class predictions output by scikit-learn.**

In [240]:
# Manually calculate predicted classes
x1 = new_X.iloc[1]['PAY_1']
x2 = new_X.iloc[1]['LIMIT_BAL']
val = coeff[0][0]*x1 + coeff[0][0]*x2 +intercept[0]
z= sigmoid(val)
z

0.2758012758672418

In [241]:
# Compare to scikit-learn's predicted classes
pred[1]

0

______________________________________________________________________
**Finally, calculate ROC AUC using both scikit-learn's predicted probabilities, and your manually predicted probabilities, and compare.**

In [243]:
# Use scikit-learn's predicted probabilities to calculate ROC AUC
from sklearn import metrics
roc_auc = metrics.roc_auc_score(y_test, pred)
roc_auc

0.6243993236017156